openapi: 3.0.3
info:
    title: CRUD API
    description: CRUD API
    version: 1.0.0
servers:
    - url: http://localhost:8080
      description: dev
paths:
    /accounts:
        get:
            $ref: ./paths/accounts/get.yaml
        post:
            $ref: ./paths/accounts/post.yaml
    /accounts/{id}:
        delete:
            $ref: ./paths/accounts/{id}/delete.yaml
        get:
            $ref: ./paths/accounts/{id}/get.yaml
        patch:
            $ref: ./paths/accounts/{id}/patch.yaml
        put:
            $ref: ./paths/accounts/{id}/put.yaml
    /permissions:
        get:
            $ref: ./paths/permissions/get.yaml
        post:
            $ref: ./paths/permissions/post.yaml
    /permissions/{id}:
        delete:
            $ref: ./paths/permissions/{id}/delete.yaml
        get:
            $ref: ./paths/permissions/{id}/get.yaml
        patch:
            $ref: ./paths/permissions/{id}/patch.yaml
        put:
            $ref: ./paths/permissions/{id}/put.yaml
    /services:
        get:
            $ref: ./paths/services/get.yaml
        post:
            $ref: ./paths/services/post.yaml
    /services/{id}:
        delete:
            $ref: ./paths/services/{id}/delete.yaml
        get:
            $ref: ./paths/services/{id}/get.yaml
        patch:
            $ref: ./paths/services/{id}/patch.yaml
        put:
            $ref: ./paths/services/{id}/put.yaml
components:
    parameters:
        $ref: ./parameters/_index.yaml
    responses:
        $ref: ./responses/_index.yaml
    schemas:
        $ref: ./schemas/_index.yaml
